stages:
  training:
    cmd: python src/train.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/preprocess_data.py
    - src/train.py
    outs:
    - saved_models/model_vgg16.h5
  evaluating:
    cmd: python src/to_predict.py --config=params.yaml
    deps:
      - src/get_data.py
      - saved_models/model_vgg16.h5
    outs:
      - evaluation/report.txt