base:
  project: cnn_dvc_task
  random_state: 42
  target_col: TARGET

data_source:
  s3_source_train: data_given/train/
  s3_source_test: data_given/test/

load_data:
  raw_data_train: data_given/train/
  raw_data_test: data_given/test/

split_data:
  train_path: data_given/train
  test_path: data_given/test
  test_size: 0.2

estimators:
  Transer_learning:
    params:
      loss: 'categorical_crossentropy'
      optimizer: 'adam'
      #epochs: 1
      #batch_size: 2
      model: 'VGG16'
      #model: 'RESNET50'
      epochs: 5
      batch_size: 4
      target_size: 128

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib