base:
  project: cnn_dvc_task
  random_state: 42
  target_col: TARGET

data_source:
  s3_source_train: data_given/train/
  s3_source_test: data_given/test/

load_data:
  raw_data_train_1: data_given/train/covid
  raw_data_train_2: data_given/train/normal
  raw_data_train_3: data_given/train/viral
  raw_data_test_1: data_given/test/covid
  raw_data_test_2: data_given/test/normal
  raw_data_test_3: data_given/test/viral

split_data:
  train_path: data_given/train
  test_path: data_given/test
  test_size: 0.2

estimators:
  VGG_transer_learning:
    params:
      loss: 'categorical_crossentropy'
      optimizer: 'adam'
      epochs: 1
      batch_size: 2
      target_size: 128

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib